[template variables=ANALYSIS_TYPE]
compulsory=true
help=Type of analysis to carry out.
values="geometric mean","arithmetic mean"
widget[rose-config-edit]=metomi.rose.config_editor.valuewidget.radiobuttons.RadioButtonsValueWidget
